### ISSUE TITLE
Api's javascript/Page layout

### ISSUE THREAD

**Issue by TNielson78** [ruthiepina/Project-1#10]
API's in progress may need changes to page format.
#Page may incorporate a Modal or accordian for lyrics section.

**Comment by ruthiepina** [comment]
API functionality should be done with button events, so from a list of tracks from selected holiday playlist, you click either a 'play' icon button or some sort of handler to then handle the transfer of data from lyrics API and display it.
- working on if we have a 30 sec song preview
