### ISSUE TITLE
General acceptance criteria

### ISSUE THREAD

**Issue by HoneyBuzz94** [ruthiepina/Project-1#2]
Here's a general list of acceptance criteria for our project. We can separate these into different issues, I just wanted to let you guys look at the whole list and make comments.

GIVEN a dashboard with dropdown inputs
WHEN I select a holiday from the dropdown menu
THEN I am presented with a playlist of holiday music
WHEN I select a song from the playlist
THEN I can hear a sample of the song play
WHEN I select a song from the playlist
THEN I am presented with the lyrics for that song
WHEN I do something
THEN something is saved into local storage

**Comment by DaneLarsen1** [comment]
Looking good! the only thing im not sure about is the "WHEN I do something
THEN something is saved into local storage"
