### ISSUE TITLE
Task Assignments

### ISSUE THREAD

**Issue by TNielson78** [ruthiepina/Project-1#3]
Current assignments:
#Ruth-Spotify API usability/Countdown API
#Dane-HTML/CSS
#Sam-Presentation, local storage, Acceptance Criteria
#Travis-Issues, User story, Documentation

**Comment by ruthiepina** [comment]
countdown is super easy, will refer to this documentation if we want to implement it
https://www.solodev.com/blog/web-design/creating-a-countdown-widget-for-your-website.stml
